[needs]
id_required = false
id_length = 3
id_regex = "^[A-Za-z0-9_]{3,}"

[[needs.types]]
directive = "feat"
title = "Feature"
prefix = "F_"
color = "#8EDB8B"
style = "node"

[[needs.types]]
directive = "req"
title = "Requirement"
prefix = "R_"
color = "#BFD8D2"
style = "node"

[[needs.types]]
directive = "spec"
title = "Specification"
prefix = "S_"
color = "#FEDCD2"
style = "node"

[[needs.types]]
directive = "impl"
title = "Implementation"
prefix = "I_"
color = "#938bdbff"
style = "node"

[[needs.types]]
directive = "dd_sta"
title = "Design Decision"
prefix = "dd_sta__"
color = "#D3DB8B"
style = "node"

[[needs.types]]
directive = "dd_dyn"
title = "Design Decision"
prefix = "dd_dyn__"
color = "#D3DB8B"
style = "node"

[[needs.types]]
directive = "sw_unit"
title = "Software Unit"
prefix = "sw_unit__"
color = "#D3DB8B"
style = "node"

[[needs.types]]
directive = "sw_unit_int"
title = "Software Unit Interface"
prefix = "sw_unit_int__"
color = "#D3DB8B"
style = "node"

[[needs.extra_options]]
name = "asil"
description = "Automotive Safety Integrity Level"
schema.type = "string"
schema.enum = ["QM", "A", "B", "C", "D"]

[[needs.extra_options]]
name = "security"
description = "Security"
schema.type = "boolean"

[[needs.extra_options]]
name = "safety"
description = "Automotive Safety Integrity Level"
schema.type = "string"
schema.enum = ["QM", "ASIL_A", "ASIL_B", "ASIL_C", "ASIL_D"]

[needs.global_options]
status = {default="draft"}
safety = {default="QM"}
